### PR TITLE
Update to sprig 3

### PR DESCRIPTION
**Pull request by n-oden**
- update to sprig v3
- update testing runtime to golang 15
- bump major version to 2 since sprig3 introduces behavioral changes
  and drops support for go <=1.14

### CODE REVIEW

**Comment by n-oden** [comment]
The proximate motivation here is that the `divf` function didn't appear in sprig until v3. :)

**Comment by n-oden** [comment]
@subfuzion gentle nudge.  :)

**Comment by chenrui333** [comment]
Should be covered in this PR, https://github.com/chenrui333/envtpl/pull/5

**Comment by n-oden** [comment]
@chenrui333 oh, thank you!  This repo does seem to have been abandoned, and I had been debating whether it was a good idea to start trying to direct attention to our fork.  Happy to see that someone else has taken up the banner!

@subfuzion should I just close this PR? Totally understood if this isn't a project you're spending time on these days.

**Comment by subfuzion** [comment]
Hi @n-oden! I'm focused on JavaScript advocacy these days and I'd pretty much forgotten about this repo. I didn't even realize anyone was using it. Thanks for the nudge. I'm going to merge this and check out the other PRs as well.

**Comment by n-oden** [comment]
Oh hey, happy new year!  I took a vacation and never noticed that in fact this had been merged.  Thank you!

And for the record, we've been very happily using this project for several years now in various different places, including here: https://engineering.oden.io/blog/pgpool-cloudsql

**Pull request merged**
